import DifferentialGeometry.VectorField

-- Synthetic Algebra
import DifferentialGeometry.Synthetic.Algebra.VectorFieldAlgebra
import DifferentialGeometry.Synthetic.Algebra.TensorAlgebra
import DifferentialGeometry.Synthetic.Algebra.Metric

-- Synthetic Analysis
import DifferentialGeometry.Synthetic.Analysis.NablaOnTensors
import DifferentialGeometry.Synthetic.Analysis.TimeOnTensors
import DifferentialGeometry.Synthetic.Analysis.NablaTimeInteraction

-- Synthetic Geometry
import DifferentialGeometry.Synthetic.Geometry.Connection
import DifferentialGeometry.Synthetic.Geometry.ConnectionExtended

-- Synthetic Operators
import DifferentialGeometry.Synthetic.Operator.Bochner
import DifferentialGeometry.Synthetic.Operator.CovariantDerivative
import DifferentialGeometry.Synthetic.Operator.Divergence
import DifferentialGeometry.Synthetic.Operator.Gradient
import DifferentialGeometry.Synthetic.Operator.Hessian
import DifferentialGeometry.Synthetic.Operator.Laplacian
import DifferentialGeometry.Synthetic.Operator.LieDerivative
import DifferentialGeometry.Synthetic.Operator.SecondCovariantDerivative
import DifferentialGeometry.Synthetic.Operator.SpatialConstant
import DifferentialGeometry.Synthetic.Operator.Variation

-- Axiom Interface
import DifferentialGeometry.Synthetic.Axioms

-- Ricci Flow
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Basic
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Calculus
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Connection
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Gradient
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Laplacian
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.ScalarCurvature
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Ricci
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.RiemannVariation
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.RiemannLaplacian
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.RiemannEvolution
