import DifferentialGeometry.Bridge.Defs

import DifferentialGeometry.Synthetic.Algebra.VectorField
import DifferentialGeometry.Synthetic.Algebra.BilinearForm
import DifferentialGeometry.Synthetic.Algebra.Metric
import DifferentialGeometry.Synthetic.Algebra.Trace

import DifferentialGeometry.Synthetic.Geometry.Bianchi
import DifferentialGeometry.Synthetic.Geometry.Conformal
import DifferentialGeometry.Synthetic.Geometry.Connection
import DifferentialGeometry.Synthetic.Geometry.Curvature
import DifferentialGeometry.Synthetic.Geometry.CurvatureTensor
import DifferentialGeometry.Synthetic.Geometry.RicciIdentity


import DifferentialGeometry.Synthetic.Geometry.RicciTensor
import DifferentialGeometry.Synthetic.Analysis.TensorInnerProduct
import DifferentialGeometry.Synthetic.Algebra.Trace

import DifferentialGeometry.Synthetic.Operator.Bochner
import DifferentialGeometry.Synthetic.Operator.CovariantDerivative
import DifferentialGeometry.Synthetic.Operator.Divergence
import DifferentialGeometry.Synthetic.Operator.Gradient
import DifferentialGeometry.Synthetic.Operator.Hessian
import DifferentialGeometry.Synthetic.Operator.Laplacian
import DifferentialGeometry.Synthetic.Operator.LieDerivative
import DifferentialGeometry.Synthetic.Operator.SecondCovariantDerivative
import DifferentialGeometry.Synthetic.Operator.SpatialConstant
import DifferentialGeometry.Synthetic.Operator.Time
import DifferentialGeometry.Synthetic.Operator.Variation

import DifferentialGeometry.Synthetic.Flow.RicciFlow.Basic
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Gradient
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Connection
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Laplacian
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.ScalarCurvature
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Evolution.Ricci
import DifferentialGeometry.Synthetic.Flow.RicciFlow.Calculus
