import DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge.SubstitutionDischargeChartBilinear
import DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge.SubstitutionDischargeGradTendsto
import DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge.SubstitutionDischargeIBP
import DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge.SubstitutionDischargeIBPExpand
import DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge.SubstitutionDischargeSmoothApprox

/-!
# DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge

Aggregated headline for `DifferentialGeometry.Analysis.Sobolev.Nirenberg.ChartBilinearDischarge`.
-/
