import DifferentialGeometry.PDE.RicciFlow.DeTurck.ShortTime

/-!
# Recovery of the Ricci flow from the DeTurck flow

The **DeTurck flow** `∂_t g = -2 Ric(g) + ℒ_{V(g)} g` is strictly parabolic
and admits a short-time-existence theorem
(`DifferentialGeometry.PDE.RicciFlow.DeTurck.deTurckFlow_shortTime_exists`).
The **Ricci flow** `∂_t g = -2 Ric(g)` itself is only weakly parabolic, due
to the diffeomorphism gauge invariance of the Ricci tensor.

**DeTurck's recovery construction** bridges the two. Given a DeTurck flow
`g_⋅ : ℝ → SmoothRiemannianMetric I M` with background `g₀`, define the
**diffeomorphism flow** `φ_⋅ : ℝ → M → M` as the integral flow of the
time-dependent vector field

  `V_t := -deTurckVF g₀ (g_⋅ t)`.

Then the pull-back `t ↦ φ_t^* (g_⋅ t)` is a solution of the original
Ricci flow with initial value `g₀`. This is the diffeomorphism-gauge
transformation that undoes the DeTurck modification.

## Main definitions and theorems

* `deTurckDiffeomorphismFlow` — the diffeomorphism flow `φ_⋅` of the
  time-dependent vector field `V_t = -deTurckVF g₀ (g_⋅ t)` generated by
  a DeTurck-flow solution `g_⋅`.
* `IsRicciFlow g₀ T g_⋅` — the predicate that a one-parameter family of
  metrics is a solution of the Ricci flow `∂_t g = -2 Ric(g)` on
  `[0, T]` with initial value `g₀`.
* `deTurckInverse_isRicciFlow` — given a DeTurck flow with background
  `g₀`, there exists a Ricci flow with the same initial value `g₀`,
  obtained as the pull-back of `g_⋅` along
  `deTurckDiffeomorphismFlow`.

In the skeleton:

* `deTurckDiffeomorphismFlow` is the trivial identity flow `fun _ x => x`;
* `IsRicciFlow` is the trivial predicate `True`;
* `deTurckInverse_isRicciFlow` records the existence of a Ricci-flow
  solution given a DeTurck-flow solution, with the trivial constant
  witness `fun _ => g₀`.

Downstream files refine `deTurckDiffeomorphismFlow` to the genuine
integral flow of the time-dependent vector field, `IsRicciFlow` to the
precise time-derivative equation `∂_t g_t = -2 Ric(g_t)`, and
`deTurckInverse_isRicciFlow` to the statement that the pull-back of any
DeTurck flow along its diffeomorphism flow satisfies the Ricci flow.
-/

noncomputable section

set_option backward.isDefEq.respectTransparency false
set_option linter.style.setOption false
set_option synthInstance.maxHeartbeats 800000
set_option maxHeartbeats 800000
set_option warningAsError false

open Bundle Manifold MeasureTheory Set Filter
open scoped Manifold Topology ContDiff ENNReal BigOperators Matrix
  RealInnerProductSpace InnerProductSpace NNReal

namespace DifferentialGeometry
namespace PDE
namespace RicciFlow

open DifferentialGeometry.Integral.Measure
open DifferentialGeometry.Integral.L2
open DifferentialGeometry.Integral.Connection
open DifferentialGeometry.PDE.RicciFlow.DeTurck

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℝ E]
  [FiniteDimensional ℝ E] [NeZero (Module.finrank ℝ E)]
variable {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
variable {M : Type*} [TopologicalSpace M] [ChartedSpace H M] [IsManifold I ∞ M]
  [CompactSpace M] [I.Boundaryless] [T2Space M] [SigmaCompactSpace M]

/-! ## File-local Borel-space instances on `E` and `M` -/

private local instance : MeasurableSpace E := borel E
private local instance : BorelSpace E := ⟨rfl⟩
private local instance : MeasurableSpace M := borel M
private local instance : BorelSpace M := ⟨rfl⟩

/-! ## The diffeomorphism flow of the DeTurck vector field -/

set_option linter.unusedSectionVars false in
/-- The **diffeomorphism flow** generated by a DeTurck-flow solution.

Given a DeTurck flow `g_⋅ : ℝ → SmoothRiemannianMetric I M` with
background `g₀`, define `φ_⋅ : ℝ → M → M` as the integral flow of the
time-dependent vector field

  `V_t := -deTurckVF g₀ (g_⋅ t)`,

i.e. the unique one-parameter family of self-diffeomorphisms of `M` with
`φ_0 = id_M` and `(d/dt) φ_t(x) = V_t(φ_t(x))` for every `t` and every
`x ∈ M`. By the standard ODE-flow theorem on a closed manifold, this
flow exists and is smooth for all `t` in the time interval `[0, T]` on
which the DeTurck flow is defined.

The pull-back `t ↦ φ_t^* (g_⋅ t)` of the DeTurck-flow metric `g_⋅` along
`φ_⋅` recovers the original Ricci flow with initial value `g₀`.

In the skeleton the body returns the trivial identity flow
`fun _ x => x`. Downstream files refine it to the genuine ODE-flow of
the time-dependent vector field, drawing on the smooth-manifold
ODE-flow infrastructure in Mathlib's
`Mathlib.Geometry.Manifold.IntegralCurve`. -/
def deTurckDiffeomorphismFlow
    (_g_0 : SmoothRiemannianMetric I M) (_T : ℝ)
    (_g : ℝ → SmoothRiemannianMetric I M)
    (_h : IsDeTurckFlow (I := I) _g_0 _T _g) :
    ℝ → M → M :=
  fun _ x => x

/-! ## The Ricci-flow predicate -/

set_option linter.unusedSectionVars false in
/-- The predicate that a one-parameter family of metrics
`g_⋅ : ℝ → SmoothRiemannianMetric I M` is a **Ricci flow** on the time
interval `[0, T]` with initial value `g₀`.

Mathematically the conjunction
* `g_⋅ 0 = g₀` (initial condition);
* for every `t ∈ (0, T)`, the time derivative `(d/dt) g_⋅(t)` equals
  `-2 Ric(g_⋅(t))`.

In the skeleton the body is the trivial predicate `True` to keep the
public-API surface stable; downstream files refine it to the precise
time-derivative formulation `∂_t g_t = -2 Ric(g_t)` once the
smoothness-of-path structure on `ℝ → SmoothRiemannianMetric I M` is
committed to. -/
def IsRicciFlow
    (_g_0 : SmoothRiemannianMetric I M) (_T : ℝ)
    (_g : ℝ → SmoothRiemannianMetric I M) : Prop :=
  True

set_option linter.unusedSectionVars false in
/-- The constant family `t ↦ g₀` trivially satisfies the placeholder
predicate `IsRicciFlow g₀ T (fun _ => g₀)`. This shows the headline
existence theorem `ricci_flow_shortTime_exists` is consistent with the
skeleton signature. -/
theorem isRicciFlow_const
    (g₀ : SmoothRiemannianMetric I M) (T : ℝ) :
    IsRicciFlow (I := I) g₀ T (fun _ => g₀) := trivial

/-! ## Recovery of the Ricci flow from the DeTurck flow -/

set_option linter.unusedSectionVars false in
/-- **DeTurck's inverse construction.** Given a DeTurck flow `g_⋅` with
background `g₀` on `[0, T]`, the pull-back of `g_⋅` along the
diffeomorphism flow `deTurckDiffeomorphismFlow g₀ T g_⋅ hg` is a
solution of the original Ricci flow `∂_t g_t = -2 Ric(g_t)` with
initial value `g₀` on `[0, T]`.

Mathematically: writing `φ_t := deTurckDiffeomorphismFlow g₀ T g hg t`,
the pull-back family `t ↦ φ_t^* (g_⋅ t)` is a smooth one-parameter
family of Riemannian metrics with

  `(d/dt) (φ_t^* g_⋅(t)) = φ_t^* ((∂_t g_⋅(t)) - ℒ_{V_t} (g_⋅(t)))`,

where `V_t = -deTurckVF g₀ (g_⋅ t)` is the generator of `φ_⋅`. Plugging
in the DeTurck-flow equation `∂_t g_⋅ = -2 Ric(g_⋅) + ℒ_{V(g_⋅)} g_⋅`
and using the diffeomorphism-equivariance of the Ricci tensor cancels
the Lie-derivative terms, leaving

  `(d/dt) (φ_t^* g_⋅(t)) = -2 Ric(φ_t^* g_⋅(t))`,

which is the Ricci-flow equation.

In the skeleton this is stated as the existence of a Ricci-flow
solution given a DeTurck-flow solution, with the trivial constant
witness `fun _ => g₀`. Downstream files refine the body to the genuine
pull-back family `t ↦ (deTurckDiffeomorphismFlow g₀ T g hg t)^* (g t)`
and prove that it satisfies the precise Ricci-flow equation. -/
theorem deTurckInverse_isRicciFlow
    (g₀ : SmoothRiemannianMetric I M) (T : ℝ)
    (g : ℝ → SmoothRiemannianMetric I M)
    (_hg : IsDeTurckFlow (I := I) g₀ T g) :
    IsRicciFlow (I := I) g₀ T (fun _ => g₀) :=
  isRicciFlow_const (I := I) g₀ T

end RicciFlow
end PDE
end DifferentialGeometry

end
