import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.Semigroup
import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.SemigroupLaw
import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.SemigroupTimeRegularity
import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.SmoothingHs
import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.SpectralBounds
import DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation.SpectralBoundsCalculus

/-!
# DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation

Aggregated headline for `DifferentialGeometry.Analysis.Parabolic.TensorHeatEquation`.
-/
