import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTower.Grid

noncomputable section

namespace DifferentialGeometry.Analysis.Spectral

abbrev tGridCount := CurvatureCoefficientDifferenceJetTower.tGridCount
alias tGridCount_nonneg := CurvatureCoefficientDifferenceJetTower.tGridCount_nonneg
alias prodTerm_le_antidiagonalTupleGrid :=
  CurvatureCoefficientDifferenceJetTower.prodTerm_le_antidiagonalTupleGrid
alias antidiagonalTupleGrid_mul_le :=
  CurvatureCoefficientDifferenceJetTower.antidiagonalTupleGrid_mul_le
alias curvDiffGrid_integral_ballUniform_window :=
  CurvatureCoefficientDifferenceJetTower.curvDiffGrid_integral_ballUniform_window
abbrev tWindow := CurvatureCoefficientDifferenceJetTower.tWindow
alias tWindow_nonneg := CurvatureCoefficientDifferenceJetTower.tWindow_nonneg
alias antidiagonalTupleGrid_le_tWindow :=
  CurvatureCoefficientDifferenceJetTower.antidiagonalTupleGrid_le_tWindow
alias tWindow_mono := CurvatureCoefficientDifferenceJetTower.tWindow_mono
alias one_le_tWindow := CurvatureCoefficientDifferenceJetTower.one_le_tWindow
abbrev tWindowMulConst := CurvatureCoefficientDifferenceJetTower.tWindowMulConst
alias tWindowMulConst_nonneg := CurvatureCoefficientDifferenceJetTower.tWindowMulConst_nonneg
alias tWindow_mul_antidiagonalTupleGrid_le :=
  CurvatureCoefficientDifferenceJetTower.tWindow_mul_antidiagonalTupleGrid_le
alias tWindow_eq_tripleSum := CurvatureCoefficientDifferenceJetTower.tWindow_eq_tripleSum
alias antidiagonalTupleGrid_eq_doubleSum :=
  CurvatureCoefficientDifferenceJetTower.antidiagonalTupleGrid_eq_doubleSum

end DifferentialGeometry.Analysis.Spectral
