import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTower.TraceGrid

namespace DifferentialGeometry.Analysis.Spectral

alias appCcRS_add_left_local := CurvatureCoefficientDifferenceJetTower.appCcRS_add_left_cc
alias appCcRS_slotInsert_id_eq :=
  CurvatureCoefficientDifferenceJetTower.appCcRS_slotInsert_id_eq
alias appCcRS_sub_left_local := CurvatureCoefficientDifferenceJetTower.appCcRS_sub_left_cc
alias appCcRS_sub_right_cc := CurvatureCoefficientDifferenceJetTower.appCcRS_sub_right_cc

alias exists_fiberNormSq_iteratedCovGrad_pairTraceOp_diff_grid :=
  CurvatureCoefficientDifferenceJetTower.exists_rfns_iteratedCovGrad_pairTraceOp_diff_grid

alias iteratedCovGrad_zero_of_covGrad_zero :=
  CurvatureCoefficientDifferenceJetTower.iteratedCovGrad_zero_of_covGrad_zero

alias pairTraceOp := CurvatureCoefficientDifferenceJetTower.pairTraceOp
alias pairTraceOp_self_eq := CurvatureCoefficientDifferenceJetTower.pairTraceOp_self_eq

alias riemannCoeff_eq_pairTrace :=
  CurvatureCoefficientDifferenceJetTower.riemannCoeff_eq_pairTrace_L11
alias riemannMixedCoeff_eq_pairTrace :=
  CurvatureCoefficientDifferenceJetTower.riemannMixedCoeff_eq_pairTrace_L01

alias rsDomDomCongrSection_sub_cc :=
  CurvatureCoefficientDifferenceJetTower.rsDomDomCongrSection_sub_cc
alias slotExtend_sub_cc := CurvatureCoefficientDifferenceJetTower.slotExtend_sub_cc

end DifferentialGeometry.Analysis.Spectral
