import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTower.Envelope
import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTowerPairTraceRepresentationDiagonalGridBound

namespace DifferentialGeometry.Analysis.Spectral

alias riemannianFiberNormSq_iteratedCovGrad_riemannCoeff_metricFactorTelescope_traceConversion_le :=
  rfns_iteratedCovGrad_riemannCoeff_metricFactorTelescope_traceConversion_le

alias riemannianFiberNormSq_iteratedCovGrad_riemannMixedCoeff_bgDiff_diagGrid_le :=
  rfns_iteratedCovGrad_riemannMixedCoeff_backgroundDifference_diagonalProductGrid_le

alias riemannianFiberNormSq_iteratedCovGrad_riemannCoeff_metricFactorTelescope_diagonalProductGrid_le :=
  rfns_iteratedCovGrad_riemannCoeff_metricFactorTelescope_diagonalProductGrid_le

alias riemannianFiberNormSq_iteratedCovGrad_ricciArmOrder0RiemannCoeff_bgDiff_diagGrid_le :=
  rfns_iteratedCovGrad_ricciArmOrder0RiemannCoeff_backgroundDifference_diagonalProductGrid_le

end DifferentialGeometry.Analysis.Spectral
