import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTower.PairTrace

namespace DifferentialGeometry.Analysis.Spectral

alias riemannianFiberNormSq_iteratedCovGrad_ricciMixedSharpBackgroundDifference_diagonalProductGrid_le :=
  rfns_iteratedCovGrad_ricciMixedSharpBackgroundDifference_diagonalProductGrid_le

alias riemannianFiberNormSq_iteratedCovGrad_slotInsertEndoCc_zero_ricEndoBgDiff_diagGrid_le :=
  rfns_iteratedCovGrad_slotInsertEndoCc_zero_ricEndoBackgroundDifferenceField_diagonalProductGrid_le

end DifferentialGeometry.Analysis.Spectral
