import DifferentialGeometry.Analysis.Spectral.Tensor.CovGrad.CurvatureCoefficientDifferenceJetTower.TraceGrid

namespace DifferentialGeometry.Analysis.Spectral

alias iteratedCovGrad_smul_b :=
  CurvatureCoefficientDifferenceJetTower.iteratedCovGrad_smul_b

alias rfns_smul_b := CurvatureCoefficientDifferenceJetTower.rfns_smul_b

alias riemannianFiberNormSq_iteratedCovGrad_riemannMixedCoeff_bgDiff_le_loweredDiff :=
  rfns_iteratedCovGrad_riemannMixedCoeff_backgroundDifference_le_loweredDifference

alias riemannianFiberNormSq_iteratedCovGrad_riemannLoweredCcFirstArgDifference_diagonalProductGrid_le :=
  rfns_iteratedCovGrad_riemannG1LoweringDifference_diagonalProductGrid_le

end DifferentialGeometry.Analysis.Spectral
