import DifferentialGeometry.Geometry.Boundary.BoundaryGramMatrix
import DifferentialGeometry.Geometry.Boundary.BoundaryManifold
import DifferentialGeometry.Geometry.Boundary.EuclideanHalfSpaceInstance
import DifferentialGeometry.Geometry.Boundary.InducedMetric
import DifferentialGeometry.Geometry.Boundary.ModelBoundary
import DifferentialGeometry.Geometry.Boundary.Orientation
import DifferentialGeometry.Geometry.Boundary.OutwardNormal
import DifferentialGeometry.Geometry.Boundary.SecondFundamentalForm
import DifferentialGeometry.Geometry.Boundary.SurfaceMeasure

/-!
# DifferentialGeometry.Geometry.Boundary

Aggregated headline for `DifferentialGeometry.Geometry.Boundary`.
-/
