import DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev.PerAlphaGradIntrinsic
import DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev.PerChartGradientL2Headline
import DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev.TensorChartComponentSobolevIntrinsic
import DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev.TensorComponentScalarWkpBound
import DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev.TensorReverseBridgeChristoffel

/-!
# DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev

Aggregated headline for `DifferentialGeometry.Analysis.Sobolev.HebeyBlock.TensorChartComponentSobolev`.
-/
