import DifferentialGeometry.Analysis.Spectral.Intrinsic.DeTurck.DeTurckRemainderTameLipschitzLieArmChartValue

namespace DifferentialGeometry.PDE.RicciFlow.IntrinsicSpectral

alias lieOne_cov_eq_raw := lieArm_arm1_value_eq_order1Raw_add_tail

end DifferentialGeometry.PDE.RicciFlow.IntrinsicSpectral
