import DifferentialGeometry.Geometry.Comparison.HopfRinow
import DifferentialGeometry.Geometry.Comparison.Volume.BishopLocal
import DifferentialGeometry.Geometry.Comparison.Volume.SegmentBallContinuity
import DifferentialGeometry.Geometry.Comparison.Volume.SegmentBallEuclideanUpper
import DifferentialGeometry.Geometry.Comparison.Volume.SegmentCount
import DifferentialGeometry.Geometry.Comparison.Volume.SegmentBallEuclideanStrict
import DifferentialGeometry.Geometry.Comparison.Volume.SegmentIntegral
import DifferentialGeometry.Geometry.Comparison.CGTVolumeInjectivity
import DifferentialGeometry.Geometry.Comparison.Busemann
import DifferentialGeometry.Geometry.Comparison.BusemannLaplacian
import DifferentialGeometry.Geometry.Comparison.BusemannLineLaplacian
import DifferentialGeometry.Geometry.Comparison.BusemannLineEnergy
import DifferentialGeometry.Geometry.Comparison.DistanceRadialIntegral
import DifferentialGeometry.Geometry.Comparison.LaplacianViscosity
import DifferentialGeometry.Analysis.Elliptic.LipschitzSupersolution
import DifferentialGeometry.Analysis.Elliptic.DistribSupersolution
import DifferentialGeometry.Analysis.Elliptic.MetricEllipticCoeff
import DifferentialGeometry.Analysis.Elliptic.WeakLaplacian
import DifferentialGeometry.Analysis.Elliptic.Operator.ChartMeasureEquiv
import DifferentialGeometry.Analysis.Sobolev.Euclidean.LipschitzW1
import DifferentialGeometry.Analysis.Sobolev.Manifold.Lipschitz
import DifferentialGeometry.External.DeGiorgi.SobolevSpace.PositiveTestDensity
import DifferentialGeometry.External.DeGiorgi.StrongMinimum
import DifferentialGeometry.Geometry.Comparison.BusemannLineSolution
import DifferentialGeometry.Geometry.Compactness.CheegerGromov.BoundedGeometry.CGTDecay
import DifferentialGeometry.Geometry.Flow.RicciFlow.Compactness.Foundations.NoncollapseInjectivity

set_option autoImplicit false

#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_rel
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_pow
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_le_euclidean
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_card
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.exists_euclid_ratio
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_cont
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.expJac_map_eq
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.expJac_lintegral
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segInt_lintegral
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.expJac_radial

#print axioms DifferentialGeometry.Geometry.Riemannian.HopfRinow.endpointCont_of_lim
#print axioms DifferentialGeometry.Geometry.Riemannian.HopfRinow.endpointCont_compact
#print axioms DifferentialGeometry.Geometry.Riemannian.HopfRinow.geo_Ioo_extend_cpt

#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.normalHaar_eq
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.gBall_model_eucl
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.transDens_eq_rigid
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.expJac_lt_of_ricci
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_lt
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_vol_lt_eucl

#print axioms DifferentialGeometry.rm04_eq_inner_riem
#print axioms DifferentialGeometry.Geometry.Riemannian.BonnetMyers.ricci_nonneg_of_sec
#print axioms DifferentialGeometry.Geometry.Riemannian.BonnetMyers.ricci_pos_of_sec
#print axioms DifferentialGeometry.Geometry.Riemannian.BonnetMyers.ricciLower_of_sec
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.segBall_lt_of_sec

#print axioms DifferentialGeometry.Geometry.Riemannian.NormalCoordinates.intrFrame_mem_eball
#print axioms DifferentialGeometry.Geometry.Riemannian.NormalCoordinates.framedExp_not_conj
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.intrInj_ge_cgt
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.intrInj_ge_cgt_on
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.intrInj_ge_vol
#print axioms DifferentialGeometry.HCGCompactness.injDecay_of_bg
#print axioms DifferentialGeometry.HCGCompactness.injDecay_realizes
#print axioms DifferentialGeometry.HCGCompactness.flowInj_of_vol

#print axioms DifferentialGeometry.Geometry.Riemannian.HopfRinow.properSpace_riemMetric
#print axioms DifferentialGeometry.Geometry.Riemannian.exists_minRay

#print axioms DifferentialGeometry.Geometry.Riemannian.busemann_tendsto
#print axioms DifferentialGeometry.Geometry.Riemannian.busemann_dist
#print axioms DifferentialGeometry.Geometry.Riemannian.busemann_ray

#print axioms DifferentialGeometry.Geometry.Riemannian.branchLap_eq_mean
#print axioms DifferentialGeometry.Geometry.Riemannian.radialLap_eq_mean
#print axioms DifferentialGeometry.Geometry.Riemannian.VolumeComparison.exists_intrMean_on
#print axioms DifferentialGeometry.calabiDist_support
#print axioms DifferentialGeometry.lapBarAt_of_support
#print axioms DifferentialGeometry.dist_lap_barrier
#print axioms DifferentialGeometry.Geometry.Operator.laplacian_sub_at
#print axioms DifferentialGeometry.IsLapLEBarrierAt.to_viscosity

#print axioms DifferentialGeometry.Integral.DivergenceTheorem.green_second_of_supp
#print axioms DifferentialGeometry.Integral.DivergenceTheorem.integral_eq_chart
#print axioms DifferentialGeometry.Analysis.Laplacian.ChartMeasureEquiv.integral_euclid
#print axioms DifferentialGeometry.IsLapLEDistribOn.mono
#print axioms DifferentialGeometry.lapDistrib_of_smooth
#print axioms DifferentialGeometry.dist_pairing_le
#print axioms DifferentialGeometry.dist_lap_distrib
#print axioms DifferentialGeometry.busemann_lap
#print axioms DifferentialGeometry.Geometry.Riemannian.IsMinimizingLine.pos_ray
#print axioms DifferentialGeometry.Geometry.Riemannian.buse_pair_nonneg
#print axioms DifferentialGeometry.Geometry.Riemannian.buse_pair_line
#print axioms DifferentialGeometry.IsLapLEDistribOn.add
#print axioms DifferentialGeometry.buse_pair_lap
#print axioms DifferentialGeometry.IsLapLEDistribOn.neg_int_le_energy
#print axioms DifferentialGeometry.IsLapLEDistribOn.lip_energy_nonneg
#print axioms DifferentialGeometry.buse_pair_memW1p
#print axioms DifferentialGeometry.Analysis.Sobolev.Euclidean.memW1p_ball_of_lip
#print axioms DifferentialGeometry.Analysis.Sobolev.Chart.raw_memW1p_of_lip
#print axioms DeGiorgi.MemH01.nonneg_approx
#print axioms DifferentialGeometry.Analysis.Laplacian.MetricExtension.exists_metric_coeff
#print axioms DeGiorgi.super_zero_ball
#print axioms DeGiorgi.super_zero_on_ball
#print axioms DifferentialGeometry.Analysis.Laplacian.DistribSupersolution.chart_super_of_lap
#print axioms DifferentialGeometry.buse_pair_eq_zero
#print axioms DifferentialGeometry.busemann_chart_sol
