import Mathlib.Topology.Bases
import Mathlib.Topology.Connected.LocPathConnected
import Mathlib.Topology.Connected.PathConnected
import Mathlib.Topology.Homotopy.Path
import DifferentialGeometry.Geometry.Riemannian.Topology.SemilocallySimplyConnected

/-!
# Universal cover of a topological space (carrier + slice topology)

We give the standard "Hatcher" construction of the universal cover of a
based topological space, as a sigma of path-homotopy classes from the
basepoint. We equip it with the *slice topology* generated by the basic
opens

  `basicOpen p U = { q | ∃ η : Path p.1 q.1, range η ⊆ U ∧ q.2 = p.2.trans ⟦η⟧ }`,

show that these opens form a topological basis (assuming the base is
locally path connected), and prove that the projection map is continuous.

The semi-local simple connectedness hypothesis is *not* needed for the
basis property; it is required separately for the sheet bijection on
"good" neighbourhoods (Hatcher Prop 1.39), which lives in a downstream
file.
-/

open Set Function Filter
open scoped Topology ContDiff

noncomputable section

namespace DifferentialGeometry
namespace Geometry
namespace Riemannian
namespace Topology
namespace UniversalCover

variable {X : Type*} [TopologicalSpace X] [Inhabited X]

/-- The carrier of the universal cover of a based topological space `X`
(with basepoint `default : X`): pairs `(x, [γ])` where `γ` is a path from
`default` to `x` and `[γ]` is its path-homotopy class. -/
def _root_.DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover
    (X : Type*) [TopologicalSpace X] [Inhabited X] : Type _ :=
  (x : X) × _root_.Path.Homotopic.Quotient (default : X) x

/-- Projection from the universal cover to the base space: extract the
endpoint of the path-class. -/
def proj :
    DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X → X :=
  Sigma.fst

/-- The basic open of the slice topology on the universal cover.
Given a point `p` of the universal cover and an open neighbourhood `U` of
`p.1` in the base, `basicOpen p U hU hp` is the set of cover-points
reachable from `p` by appending a path that stays inside `U`. -/
def basicOpen
    (p : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X)
    (U : Set X) (_hU : IsOpen U) (_hp : p.1 ∈ U) :
    Set (DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X) :=
  { q | ∃ η : _root_.Path p.1 q.1,
          (∀ t, η t ∈ U) ∧
            q.2 =
              (p.2.trans
                ((_root_.Path.Homotopic.Quotient.mk η :
                    _root_.Path.Homotopic.Quotient p.1 q.1))) }

/-- The slice topology on the universal cover: the topology generated by
the basic opens `basicOpen p U _ _`. -/
instance topology :
    TopologicalSpace
      (DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X) :=
  TopologicalSpace.generateFrom
    { S | ∃ (p : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X)
            (U : Set X) (hU : IsOpen U) (hp : p.1 ∈ U),
              S = basicOpen p U hU hp }

/-- **Transitive shift along a sub-neighbourhood.**
If `q` lies in `basicOpen p U` via a path `η` that stays in `U`, and
`r` lies in `basicOpen q U'` via a path `η'` that stays in `U' ⊆ U`,
then `r` lies in `basicOpen p U` via the concatenated path `η.trans η'`.
This is associativity of path concatenation modulo homotopy. -/
theorem basis_trans_shift
    {p q r : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X}
    {U U' : Set X} (hU : IsOpen U) (hp : p.1 ∈ U)
    (hU' : IsOpen U') (hq : q.1 ∈ U') (hsub : U' ⊆ U)
    (hqp : q ∈ basicOpen p U hU hp)
    (hrq : r ∈ basicOpen q U' hU' hq) :
    r ∈ basicOpen p U hU hp := by
  sorry

/-- **Intersection of basic opens contains a basic open.**
On a locally path-connected base, for any point `r` lying in two basic
opens `basicOpen p₁ U₁` and `basicOpen p₂ U₂`, there is an open
path-connected neighbourhood `V ⊆ U₁ ∩ U₂` of `r.1` such that
`basicOpen r V` is contained in their intersection. -/
theorem basis_intersection
    [LocPathConnectedSpace X]
    {p₁ p₂ r : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X}
    {U₁ U₂ : Set X} (hU₁ : IsOpen U₁) (hp₁ : p₁.1 ∈ U₁)
    (hU₂ : IsOpen U₂) (hp₂ : p₂.1 ∈ U₂)
    (hr : r ∈ basicOpen p₁ U₁ hU₁ hp₁ ∩ basicOpen p₂ U₂ hU₂ hp₂) :
    ∃ (V : Set X) (hV : IsOpen V) (hrV : r.1 ∈ V),
      V ⊆ U₁ ∩ U₂ ∧ IsPathConnected V ∧
        basicOpen r V hV hrV ⊆
          basicOpen p₁ U₁ hU₁ hp₁ ∩ basicOpen p₂ U₂ hU₂ hp₂ := by
  sorry

/-- **Basic opens cover the universal cover.**
Every point `q` of the universal cover lies in some basic open
(take `p := q`, `U := univ`, `η := Path.refl q.1`). -/
theorem basis_covers
    (q : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X) :
    ∃ (p : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X)
      (U : Set X) (hU : IsOpen U) (hp : p.1 ∈ U),
        q ∈ basicOpen p U hU hp := by
  sorry

/-- **The basic opens form a topological basis.**
On a locally path-connected space, the family
`{ basicOpen p U hU hp | … }` is an `IsTopologicalBasis` for the slice
topology on the universal cover. -/
theorem basis_assemble
    [LocPathConnectedSpace X] :
    TopologicalSpace.IsTopologicalBasis
      { S : Set (DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X) |
          ∃ (p : DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X)
            (U : Set X) (hU : IsOpen U) (hp : p.1 ∈ U),
              S = basicOpen p U hU hp } := by
  sorry

/-- **The projection is continuous.**
Each basic open `basicOpen p U hU hp` maps under `proj` into `U`, so the
preimage of any open of `X` is a union of basic opens. -/
theorem proj_continuous [LocPathConnectedSpace X] :
    Continuous
      (proj :
        DifferentialGeometry.Geometry.Riemannian.Topology.UniversalCover X → X) := by
  sorry

end UniversalCover
end Topology
end Riemannian
end Geometry
end DifferentialGeometry

end
