import DifferentialGeometry.Synthetic.Geometry.Connection
import DifferentialGeometry.Synthetic.Geometry.ConnectionExtended
import Mathlib.Algebra.Lie.Subalgebra
import Mathlib.Algebra.Lie.OfAssociative

/-!
# Holonomy of an Affine Connection (Ambrose–Singer form)

Classical holonomy at a point `p ∈ M` is the subgroup of `GL(E_p)` generated
by parallel transport around piecewise-smooth loops at `p`; the *restricted*
holonomy `Hol⁰` is parallel transport around null-homotopic loops. By
Ambrose–Singer, the Lie algebra of `Hol⁰` is generated by curvature
endomorphisms (and, more generally, by their iterated covariant derivatives).

The synthetic framework in this repo has no "points" and no "loops" — vector
fields and sections are algebraic objects over a scalar ring `R`. We therefore
take the *Ambrose–Singer / infinitesimal* characterization as the
**definition**:

* `restrictedHolonomyAlgebra` : the `R`-Lie subalgebra of `Module.End R V`
  generated by the curvature endomorphisms `Rm(X, Y) : V →ₗ[R] V`.
* `holonomyAlgebra` : the `R`-Lie subalgebra generated by the curvature
  endomorphisms *and* all their iterated covariant derivatives `∇^k Rm`.

On a smooth, simply-connected Riemannian manifold the Ambrose–Singer theorem
identifies these with the Lie algebra of the classical holonomy group.

## Generalization to vector bundles

The current setup is the tangent-bundle special case: `conn : V → V → V` with
the *same* module `V` for both the directional argument and the section being
differentiated. To treat a general vector bundle `E → M` one would refactor to

  `conn : V → E → E`

with `V` the vector fields on the base and `E` an `R`-module of sections. The
curvature endomorphism then lives in `Module.End R E` and the holonomy becomes
a Lie subalgebra there. The Koszul formula and metric compatibility are
specific to the tangent-bundle case, so those APIs stay here.

## Roadmap toward the Chern–Ricci goal

1. **Metric-compatible constraint**: show every `L ∈ restrictedHolonomyAlgebra`
   of a metric-compatible connection is skew-adjoint w.r.t. `g`, i.e. lives
   in `𝔰𝔬(V, g)`. Stated below as `restrictedHolonomy_skew_adjoint` with
   `sorry` — direct from `Rm_metric_antisymm` for the generators plus closure
   of skew-adjoint endomorphisms under Lie bracket and `R`-linear combinations.
2. **Chern connection** on a complex manifold (not yet present here).
3. **Invariance under Chern–Ricci flow**: formalize that
   `restrictedHolonomyAlgebra (conn_fam t)` is independent of `t`. The Ricci
   flow machinery lives in `Synthetic/Flow/RicciFlow/*`.

The bridge back to classical parallel transport (Ambrose–Singer in the smooth
setting) is left as a comment only — it would require formalizing curves and
parallel transport, which the synthetic framework deliberately avoids.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open SyntheticTensor

namespace Synthetic

-- ============================================================
-- Curvature as an R-linear endomorphism of V
-- ============================================================

section CurvatureEndomorphism

variable {k R V : Type*}
variable [Field k] [CommRing R] [Algebra k R]
variable [AddCommGroup V] [Module R V] [Module k V] [IsScalarTower k R V]

/-- The curvature endomorphism `Rm(X, Y) : V →ₗ[R] V`, packaging `R`-linearity
of `Rm emb conn X Y` in its third argument. -/
noncomputable def RmEndo
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (X Y : V) : V →ₗ[R] V where
  toFun Z := Rm emb conn X Y Z
  map_add' Z₁ Z₂ := Rm_add_Z emb conn ha hal X Y Z₁ Z₂
  map_smul' f Z := by
    simp only [RingHom.id_apply]
    exact Rm_smul_Z emb conn ha hsl hl f X Y Z

@[simp] theorem RmEndo_apply
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (X Y Z : V) :
    RmEndo emb conn ha hal hsl hl X Y Z = Rm emb conn X Y Z := rfl

end CurvatureEndomorphism

-- ============================================================
-- Covariant derivative of an R-linear endomorphism of V
-- ============================================================

section CovDerivEndo

variable {k R V : Type*}
variable [Field k] [CommRing R] [Algebra k R]
variable [AddCommGroup V] [Module R V] [Module k V] [IsScalarTower k R V]

/-- Covariant derivative `∇_W L` of an endomorphism `L : V →ₗ[R] V` along
`W`, defined via the commutator `[∇_W, L]`. The Leibniz correction in
`∇_W (L Z) = (∇_W L)(Z) + L(∇_W Z)` is exactly what makes
`Z ↦ ∇_W (L Z) - L (∇_W Z)` `R`-linear, handled by `commutatorEndo`. -/
noncomputable def covDerivEndo
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (W : V) (L : V →ₗ[R] V) : V →ₗ[R] V :=
  commutatorEndo (fun f => (emb.embed W) f) (conn W)
    (fun v w => ha W v w) (fun f v => hl W f v) L

@[simp] theorem covDerivEndo_apply
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (W : V) (L : V →ₗ[R] V) (Z : V) :
    covDerivEndo emb conn ha hl W L Z = conn W (L Z) - L (conn W Z) := rfl

end CovDerivEndo

-- ============================================================
-- Restricted (curvature-generated) holonomy Lie algebra
-- ============================================================

section RestrictedHolonomy

variable {k R V : Type*}
variable [Field k] [CommRing R] [Algebra k R]
variable [AddCommGroup V] [Module R V] [Module k V] [IsScalarTower k R V]

/-- The set of curvature endomorphisms `{ Rm(X, Y) | X Y : V }` inside
`Module.End R V`. -/
noncomputable def curvatureEndoSet
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y) :
    Set (Module.End R V) :=
  Set.range fun p : V × V => RmEndo emb conn ha hal hsl hl p.1 p.2

/-- **Restricted holonomy Lie algebra**: the `R`-Lie subalgebra of
`Module.End R V` generated by the curvature endomorphisms. Takes the role of
`𝔥𝔬𝔩⁰_p` from the classical theory. -/
noncomputable def restrictedHolonomyAlgebra
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y) :
    LieSubalgebra R (Module.End R V) :=
  LieSubalgebra.lieSpan R (Module.End R V)
    (curvatureEndoSet emb conn ha hal hsl hl)

theorem RmEndo_mem_restrictedHolonomyAlgebra
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (X Y : V) :
    RmEndo emb conn ha hal hsl hl X Y ∈
      restrictedHolonomyAlgebra emb conn ha hal hsl hl :=
  LieSubalgebra.subset_lieSpan ⟨(X, Y), rfl⟩

end RestrictedHolonomy

-- ============================================================
-- Full infinitesimal holonomy: closure under covariant derivative
-- ============================================================

section InfinitesimalHolonomy

variable {k R V : Type*}
variable [Field k] [CommRing R] [Algebra k R]
variable [AddCommGroup V] [Module R V] [Module k V] [IsScalarTower k R V]

/-- `IteratedCurvatureEndo L` iff `L` is obtained from curvature endomorphisms
`Rm(X, Y)` by (possibly zero) iterated applications of `covDerivEndo`. -/
inductive IteratedCurvatureEndo
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y) :
    Module.End R V → Prop
  | curvature (X Y : V) :
      IteratedCurvatureEndo emb conn ha hal hsl hl
        (RmEndo emb conn ha hal hsl hl X Y)
  | covDeriv (W : V) {L : Module.End R V}
      (h : IteratedCurvatureEndo emb conn ha hal hsl hl L) :
      IteratedCurvatureEndo emb conn ha hal hsl hl
        (covDerivEndo emb conn ha hl W L)

/-- **Full infinitesimal holonomy Lie algebra**: generated by curvature and all
its iterated covariant derivatives. -/
noncomputable def holonomyAlgebra
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y) :
    LieSubalgebra R (Module.End R V) :=
  LieSubalgebra.lieSpan R (Module.End R V)
    { L | IteratedCurvatureEndo emb conn ha hal hsl hl L }

end InfinitesimalHolonomy

-- ============================================================
-- Long-term goals (with `sorry`)
-- ============================================================

section Goals

variable {k R V : Type*}
variable [Field k] [CommRing R] [Algebra k R]
variable [AddCommGroup V] [Module R V] [Module k V] [IsScalarTower k R V]

/-- The Lie subalgebra of skew-adjoint endomorphisms: `{L | g(LX, Y) + g(X, LY) = 0}`.
Concrete construction (not going through `LinearMap.BilinForm`) so we can use
`met.g` directly. -/
noncomputable def skewAdjointLie (met : MetricDuality R V) :
    LieSubalgebra R (Module.End R V) where
  carrier := { L : Module.End R V | ∀ X Y, met.g (L X) Y + met.g X (L Y) = 0 }
  zero_mem' := by
    intro X Y
    change met.g ((0 : Module.End R V) X) Y + met.g X ((0 : Module.End R V) Y) = 0
    have hL : met.g ((0 : V)) Y = 0 := by
      have := met.g_smul_left (0 : R) X Y
      rwa [zero_smul, zero_mul] at this
    have hR : met.g X ((0 : V)) = 0 := by
      have := met.g_smul_right (0 : R) X Y
      rwa [zero_smul, zero_mul] at this
    simp [LinearMap.zero_apply, hL, hR]
  add_mem' := by
    intro L₁ L₂ h₁ h₂ X Y
    change met.g ((L₁ + L₂) X) Y + met.g X ((L₁ + L₂) Y) = 0
    rw [LinearMap.add_apply, LinearMap.add_apply,
        met.g_add_left, met.g_add_right]
    linear_combination h₁ X Y + h₂ X Y
  smul_mem' := by
    intro c L h X Y
    change met.g ((c • L) X) Y + met.g X ((c • L) Y) = 0
    rw [LinearMap.smul_apply, LinearMap.smul_apply,
        met.g_smul_left, met.g_smul_right]
    linear_combination c * h X Y
  lie_mem' := by
    intro L₁ L₂ h₁ h₂ X Y
    have hXY : met.g (L₁ (L₂ X)) Y + met.g (L₂ X) (L₁ Y) = 0 := h₁ (L₂ X) Y
    have hXY' : met.g (L₂ (L₁ X)) Y + met.g (L₁ X) (L₂ Y) = 0 := h₂ (L₁ X) Y
    have hYX : met.g (L₁ X) (L₂ Y) + met.g X (L₁ (L₂ Y)) = 0 := h₁ X (L₂ Y)
    have hYX' : met.g (L₂ X) (L₁ Y) + met.g X (L₂ (L₁ Y)) = 0 := h₂ X (L₁ Y)
    -- Unfold the Lie bracket on `Module.End R V`: ⁅L₁, L₂⁆ P = L₁(L₂ P) - L₂(L₁ P).
    have ebr : ∀ P, (⁅L₁, L₂⁆ : Module.End R V) P = L₁ (L₂ P) - L₂ (L₁ P) :=
      fun _ => rfl
    change met.g (⁅L₁, L₂⁆ X) Y + met.g X (⁅L₁, L₂⁆ Y) = 0
    rw [ebr X, ebr Y, sub_eq_add_neg, sub_eq_add_neg,
        met.g_add_left, met.g_neg_left, met.g_add_right, met.g_neg_right]
    linear_combination hXY - hXY' + hYX - hYX'

/-- For a metric-compatible connection, every element of the restricted
holonomy algebra is skew-adjoint with respect to `g`. Proof route:
1. Generators `Rm(X, Y)` are skew-adjoint via `Rm_metric_antisymm`.
2. Skew-adjoint endos form a Lie subalgebra (`skewAdjointLie`).
3. `LieSubalgebra.lieSpan_le` gives `restrictedHolonomyAlgebra ≤ skewAdjointLie`. -/
theorem restrictedHolonomy_skew_adjoint
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (met : MetricDuality R V) (h_mc : IsMetricCompatible emb conn met)
    (L : Module.End R V)
    (hL : L ∈ restrictedHolonomyAlgebra emb conn ha hal hsl hl) (X Y : V) :
    met.g (L X) Y + met.g X (L Y) = 0 := by
  have hgen : curvatureEndoSet emb conn ha hal hsl hl ⊆
      (skewAdjointLie (R := R) (V := V) met : Set (Module.End R V)) := by
    rintro _ ⟨⟨A, B⟩, rfl⟩ P Q
    change met.g (Rm emb conn A B P) Q + met.g P (Rm emb conn A B Q) = 0
    have h1 : met.g (Rm emb conn A B P) Q = -met.g (Rm emb conn A B Q) P :=
      Rm_metric_antisymm emb conn met h_mc A B P Q
    rw [h1, met.g_symm P (Rm emb conn A B Q), neg_add_cancel]
  have hsub : restrictedHolonomyAlgebra emb conn ha hal hsl hl ≤
      skewAdjointLie (R := R) (V := V) met :=
    (LieSubalgebra.lieSpan_le).mpr hgen
  exact hsub hL X Y

/-- Covariant derivative of a skew-adjoint endomorphism is skew-adjoint, provided
the connection is metric-compatible. -/
theorem covDerivEndo_mem_skewAdjoint
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (met : MetricDuality R V) (h_mc : IsMetricCompatible emb conn met)
    (W : V) (L : Module.End R V)
    (hL : L ∈ skewAdjointLie (R := R) (V := V) met) :
    covDerivEndo emb conn ha hl W L ∈ skewAdjointLie (R := R) (V := V) met := by
  intro X Y
  change met.g (conn W (L X) - L (conn W X)) Y +
         met.g X (conn W (L Y) - L (conn W Y)) = 0
  have mc1 : (emb.embed W) (met.g (L X) Y) =
      met.g (conn W (L X)) Y + met.g (L X) (conn W Y) := h_mc W (L X) Y
  have mc2 : (emb.embed W) (met.g X (L Y)) =
      met.g (conn W X) (L Y) + met.g X (conn W (L Y)) := h_mc W X (L Y)
  have sA : met.g (L X) Y + met.g X (L Y) = 0 := hL X Y
  have sB : met.g (L X) (conn W Y) + met.g X (L (conn W Y)) = 0 := hL X (conn W Y)
  have sC : met.g (L (conn W X)) Y + met.g (conn W X) (L Y) = 0 := hL (conn W X) Y
  have hWsum : (emb.embed W) (met.g (L X) Y + met.g X (L Y)) = 0 := by
    rw [sA]; exact map_zero _
  rw [map_add, mc1, mc2] at hWsum
  rw [sub_eq_add_neg, sub_eq_add_neg, met.g_add_left, met.g_neg_left,
      met.g_add_right, met.g_neg_right]
  linear_combination hWsum - sB - sC

/-- **Full infinitesimal holonomy is skew-adjoint.** Kotschwar's Remark 5.2:
for a metric-compatible connection, every `L ∈ holonomyAlgebra` (curvature and
all its iterated covariant derivatives) lies in `𝔰𝔬(V, g)`. -/
theorem holonomy_skew_adjoint
    (emb : DerivationEmbedding k R V) (conn : V → V → V)
    (ha : ∀ X Y Z, conn X (Y + Z) = conn X Y + conn X Z)
    (hal : ∀ X Y Z, conn (X + Y) Z = conn X Z + conn Y Z)
    (hsl : ∀ (f : R) X Z, conn (f • X) Z = f • conn X Z)
    (hl : ∀ X (f : R) Y, conn X (f • Y) = (emb.embed X) f • Y + f • conn X Y)
    (met : MetricDuality R V) (h_mc : IsMetricCompatible emb conn met)
    (L : Module.End R V)
    (hL : L ∈ holonomyAlgebra emb conn ha hal hsl hl) (X Y : V) :
    met.g (L X) Y + met.g X (L Y) = 0 := by
  have hgen : { L' | IteratedCurvatureEndo emb conn ha hal hsl hl L' } ⊆
      (skewAdjointLie (R := R) (V := V) met : Set (Module.End R V)) := by
    intro L' hL'
    induction hL' with
    | curvature A B =>
        intro P Q
        change met.g (Rm emb conn A B P) Q + met.g P (Rm emb conn A B Q) = 0
        have h1 : met.g (Rm emb conn A B P) Q = -met.g (Rm emb conn A B Q) P :=
          Rm_metric_antisymm emb conn met h_mc A B P Q
        rw [h1, met.g_symm P (Rm emb conn A B Q), neg_add_cancel]
    | covDeriv W _ ih =>
        exact covDerivEndo_mem_skewAdjoint emb conn ha hl met h_mc W _ ih
  have hsub : holonomyAlgebra emb conn ha hal hsl hl ≤
      skewAdjointLie (R := R) (V := V) met :=
    (LieSubalgebra.lieSpan_le).mpr hgen
  exact hsub hL X Y

end Goals

end Synthetic
